name: any_of
description: A Dart package for working with algebraic data types (ADTs) representing "any-of" values with multiple options.
version: 2.0.1
homepage: https://www.zooper.dev/
repository: https://github.com/zooper-lib/any_of
topics:
  - discriminated-union
funding:
  - https://buymeacoffee.com/zooperlib

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
