trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  packageName: "any_of"

steps:
  - checkout: self
    submodules: true

  # Dart installation step
  - script: |
      echo "Installing Dart SDK..."
      sudo apt-get update
      sudo apt-get install apt-transport-https
      sudo sh -c 'wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
      sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
      sudo apt-get update
      sudo apt-get install dart
    displayName: "Install Dart"

  # Authentication with pub.dev
  - script: |
      echo "Authenticating with pub.dev..."
      dart pub token add https://pub.dev --env-var=PUB_DEV_TOKEN
    displayName: "Authenticate with pub.dev"
    env:
      PUB_CACHE: $(Agent.ToolsDirectory)/.pub-cache
      PUB_DEV_TOKEN: $(PubDevToken) # This maps the Azure DevOps secret variable to an environment variable

  # Publish package
  - script: |
      echo "Publishing package to pub.dev..."
      dart pub publish --force
    displayName: "Publish Package"
    env:
      PUB_CACHE: $(Agent.ToolsDirectory)/.pub-cache
      PUB_DEV_TOKEN: $(PubDevToken)
